### ISSUE TITLE
park xl versus l, same for airport and train_station

### ISSUE THREAD

**Issue by nvkelso** [tangrams/icons#11]
<img width="902" alt="screen shot 2016-11-28 at 17 33 08" src="https://cloud.githubusercontent.com/assets/853051/20693062/cb645664-b590-11e6-9323-8cd7efbfbceb.png">

<img width="909" alt="screen shot 2016-11-28 at 17 32 59" src="https://cloud.githubusercontent.com/assets/853051/20693061/cb611800-b590-11e6-9d19-39e5ea055779.png">

<img width="915" alt="screen shot 2016-11-28 at 17 32 19" src="https://cloud.githubusercontent.com/assets/853051/20693063/cb69231a-b590-11e6-9d4b-99870840cf30.png">
rain

**Comment by sensescape** [comment]
renamed from -xl to -l

https://github.com/tangrams/tron-style/commit/9d10f29037eab14394a9ef789562d42eea5ee7df
