### ISSUE TITLE
remove mountain from Tron (keep peak)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/icons#13]
<img width="899" alt="screen shot 2016-11-28 at 17 35 29" src="https://cloud.githubusercontent.com/assets/853051/20693185/8cca9fd4-b591-11e6-9dd3-b3121f762628.png">

<img width="896" alt="screen shot 2016-11-28 at 17 35 21" src="https://cloud.githubusercontent.com/assets/853051/20693184/8cca9502-b591-11e6-9154-721926d76034.png">

**Comment by sensescape** [comment]
done:
https://github.com/tangrams/tron-style/commit/654502f6e1ce62b4f1731df6277fd3acbea39a15
