### ISSUE TITLE
tree icons broken

### ISSUE THREAD

**Issue by nvkelso** [tangrams/icons#14]
I think the one of them needs to be `tree` (for the default size), and the smaller dot should be something like `tree-s`. I think this is only for Walkabout now.

<img width="898" alt="screen shot 2016-11-28 at 17 39 29" src="https://cloud.githubusercontent.com/assets/853051/20693205/adc75592-b591-11e6-945a-40dab4448487.png">

**Comment by nvkelso** [comment]
I've committed the assets, fixing the ? icons.

But the tree icons should still be renamed.

**Comment by sensescape** [comment]
renamed

<img width="811" alt="screen shot 2016-11-29 at 1 51 14 pm" src="https://cloud.githubusercontent.com/assets/466585/20730444/f764bbc8-b63a-11e6-868f-6660308e78db.png">
https://github.com/tangrams/walkabout-style/commit/4f7710a760fc5c6d8d1332cd0693f5462b61f3ee

**Comment by nvkelso** [comment]
Verified.

**Comment by nvkelso** [comment]
(This was changed to `tree` and `tree-s`.)
