### ISSUE TITLE
Is there a sprite sheet available?

### ISSUE THREAD

**Issue by stevage** [tangrams/icons#31]
I seem to remember there being a page where you could preview all the icons. Does that still exist?

I can see individual .png files in https://github.com/tangrams/icons/blob/master/spritesheet/bubble-wrap%4016x.png but is there any HTML wrapping that together?

**Comment by nvkelso** [comment]
See:

- https://github.com/tangrams/cartography-docs/blob/master/icons.md

That should be ported to ReadTheDocs but like most the rest of the documentation already has.
