### ISSUE TITLE
icons getting cut off when other shapes are introduced

### ISSUE THREAD

**Issue by sensescape** [tangrams/icons#4]
Hi! @nvkelso 

Starting to add other shapes to the sprite sheet for Tron, but icons are now getting cropped:

<img width="480" alt="screen shot 2016-08-16 at 9 21 57 am" src="https://cloud.githubusercontent.com/assets/466585/17706991/2882cb96-6393-11e6-92b2-46921facc0cf.png">

<img width="805" alt="screen shot 2016-08-16 at 9 20 56 am" src="https://cloud.githubusercontent.com/assets/466585/17706996/2ea54134-6393-11e6-8aa8-a1899e5f7501.png">

**Comment by nvkelso** [comment]
Cool! Please make sure your Illustrator file is checked in to the icons repo and I'll have a look.

_Nathaniel

**Comment by sensescape** [comment]
Thanks! Here's the file with squares introduced, going to add pentagon and hexagon shapes too

**Comment by sensescape** [comment]
Now with hexagon badges too:
https://github.com/tangrams/icons/commit/a73122f4f7c0586383d5b34952bf140969a22e16

**Comment by nvkelso** [comment]
This was fixed a while back.
